# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(majorMinorVersion).$(semanticVersion) # $(rev:r)
# name: 1.0$(rev:.r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  majorMinorVersion: 1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Install NuGet tools'

- task: NuGetCommand@2
  displayName: 'Restore NuGet and solution'
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    testRunTitle: 'LoggerTest'

# - task: DotNetCoreCLI@2
#   displayName: 'Pack solution'
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/My.Dotnet.Logger/*.csproj'
#     versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  displayName: 'Pack My.Dotnet.Logger'
  inputs:
    command: 'pack'
    packagesToPack: '**/My.Dotnet.Logger/*.*(csproj|nuspec)'
    versioningScheme: 'byBuildNumber'

# - task: DotNetCoreCLI@2
#   displayName: 'Pack My.Dotnet.Logger'
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/My.Dotnet.Logger/*.nuspec'
#     nobuild: true
#     versioningScheme: 'byBuildNumber'

- task: DotNetCoreCLI@2
  displayName: 'Push .nuget package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '/d3882b5e-344d-4c6e-b233-8c06ee14bc16'

